### ISSUE TITLE
The KL divergence is same as in Variational Auto Encoder ? 

### ISSUE THREAD

**Issue by shamanez** [akanimax/Variational_Discriminator_Bottleneck#3]
Hi,
Your implementation is perfect and so informative. In the paper, they clearly mentioned how they simplified the mutual information constraints into KL divergence w.r.t a Gaussian distribution.  So here we take the KL divergence between two distributions rather than two random variables. I think this is the same technique that they have used in VAE calling **variational inference**. Is my understanding is correct? 

Actually, the difference is in VAE we do not explicitly talk about the information constrain and directly optimizing w.r.t the KL divergence loss. But with the I_c we have to use a Lagrangian multiplier and update the beta adaptive. 

Is my understanding is correct?

**Comment by akanimax** [comment]
Hi @shamanez,

Apologies for the late reply. I was laden with too much work and was a bit unwell on the weekend too.
Thank you for the comment and the compliments. Means a lot to me.

First of all, please note that the **KL-Divergence** cannot be calculated between two different random variables. A lot of students seem to have this confusion which I don't know why. It is a measure of divergence between two distributions over the same random variable. refer [kl-divergence-wiki](https://en.wikipedia.org/wiki/Kullback%E2%80%93Leibler_divergence) for more information.

You are right about this part that in case of VAE, we are just minimizing the KL-divergence between the predicted gaussians and the unit gaussian, whereas in VGAN, we want the KL-divergence to be specifically equal to the `I_c` that we set.

Hope this helps.

Best regards,
@akanimax

**Comment by shamanez** [comment]
Perfect answer. Thanks a lot
