### ISSUE TITLE
How sensitive the initial value for the beta parameter ? 

### ISSUE THREAD

**Issue by shamanez** [akanimax/Variational_Discriminator_Bottleneck#4]
Hi,
Here, you have used a max operation to adaptively update the beta parameters as given in the paper. So first we update the discriminator loss by using wgan-gp loss and bottleneck loss that multiplied with the **beta** parameter.  After that, we update the **beta** parameter with the max operation.  But theoretically when we updating the parameters with the dual gradients. We need to first optimize the discriminator loss and then use that optimized function and calculate the gradient w.r.t beta parameters and update it. Here why they use a max operation? Is that to make sure a monotonic improvement?   Or is that to keep the effect of the bottleneck loss to the wgan-gp loss alway positive keeping an upper bound?

**Comment by akanimax** [comment]
Hi @shamanez,

1.) please refer to the **`section 4`** of the paper where the following is written:

> In practice, we perform only one gradient step on D and E, followed by an update to β. We refer to
a GAN that incorporates a VDB as a variational generative adversarial network (VGAN).

The explanation of this simply lies in the fact that multiple stochastic iterations can still lead to convergence (Take dynamic routing protocols for example).

2.) You have too many interpretations of the `max(0, x)` operation used for updating the beta, but the actual reason for applying this `ReLU` is the **Lagrangian constraint**. If you invert the **Lagrange multiplier**, negative constraint gets applied in the Lagrangian. Please refer to this wiki [lagrange-multiplier-wiki](https://en.wikipedia.org/wiki/Lagrange_multiplier) for more info.

Hope this helps.

Best regards,
@akanimax

p.s. apology for the late reply. It has been a bit difficult for me to reply to all the queries off late.

**Comment by shamanez** [comment]
Perfect. You have amazing coding and theoretical explaining abilities. I really enjoyed all of these conversations. Thank you, sir.
