### ISSUE TITLE
 some problem

### ISSUE THREAD

**Issue by yanyuze123** [akanimax/Variational_Discriminator_Bottleneck#7]
Hello, there is some problem with my generation result, only some color blocks can be generated, do you know anything about this problem?

![gen_3_95](https://github.com/akanimax/Variational_Discriminator_Bottleneck/assets/87850364/4d6f8cc4-0704-48d8-a2dc-79ad9f7f8561)
![gen_11_139](https://github.com/akanimax/Variational_Discriminator_Bottleneck/assets/87850364/918c5d31-eb49-41f6-a32a-9e528b98c07c)
![gen_16_128](https://github.com/akanimax/Variational_Discriminator_Bottleneck/assets/87850364/581901cd-162d-4cc3-b69e-d0c4249ba458)

It seems to be spawning in a good direction, but it is very slow.

**Comment by akanimax** [comment]
Hi @yanyuze123, 

Are you training your model on CelebA dataset? It took me about 2 weeks to train the models which I have shared. Check out this linkedin post here -> https://www.linkedin.com/in/animesh-karnewar-65b3ba115/recent-activity/all/

If I remember correctly, I also saw samples like those in the beginning of the training. I'd suggest you to try training for longer. 

Best regards,
@akanimax

**Comment by yanyuze123** [comment]
Hi @akanimax ，

Thank you very much, I will try to train longer today. Also, I have a dataset with around 1000 sheets per class, do you think it is possible to use your GAN network for training?

There are many irrelevant features in the dataset, and the proportion of defective features is small.

![6_d](https://github.com/akanimax/Variational_Discriminator_Bottleneck/assets/87850364/796ffaeb-9a28-4dc8-85d0-06543f19a87f)
![2_d](https://github.com/akanimax/Variational_Discriminator_Bottleneck/assets/87850364/db8ac926-fc09-4b61-bc59-d320dd0291ba)


Best regards,
@yanyuze123

**Comment by yanyuze123** [comment]
You are right, this is the result of 3 hours of training.

I changed the random seed to speed up the generation.

![gen_261_1](https://github.com/akanimax/Variational_Discriminator_Bottleneck/assets/87850364/61b350ad-ffc3-45bf-bd4f-b3c9d83d63ac)

**Comment by akanimax** [comment]
Hey, No worries. I don't think the VDB-GAN would train with a dataset as low as 1000 samples. I'll suggest to try the differentiable augmentations similar to (https://arxiv.org/abs/2006.06676).

**Comment by yanyuze123** [comment]
Thank you very much for the advice, you are a knowledgeable person, I will read this paper and use it on my dataset ...

**Comment by akanimax** [comment]
Closing this issue.
